### ISSUE TITLE
Приветственное слово

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#1]
### Анастасия, привет!
Меня зовут Илья и я буду помогать, чем смогу, на твоём пути к становлению фронтенд-разработчиком. Надеюсь, что тебе это нравится и ты испытываешь большое желание развиваться в этом направлении)) Все проходили через этот путь и подавляющему большинству он давался с трудом. Но я уверен, что ты сможешь осилить этот путь и достичь своей цели!

Хочу поделиться своим опытом и отметить важные моменты, которые я осознал за это время:
- Не нужно бояться совершать ошибки. Мы все их совершаем, это абсолютно нормально и в программировании мы их совершаем ежедневно. Не вини себя в этом, принимай как урок и двигайся дальше
- Важно уметь воспринимать критику. Более опытные разработчики могут по-разному отзываться о твоей работе, указывать на недостатки, ошибки, пробелы в знаниях и т.п.. Важно слушать, учиться, но не воспринимать близко к сердцу)
- Соблюдай баланс. Не надо биться над проблемой целыми днями. Если понимаешь, что в течении 1-2 часов ты не можешь решить проблему, оставь её и двигайся дальше. Вернись в следующий раз к ней на свежую голову и ты сможешь если не решить её, то хорошо продвинуться вперёд. Если понимаешь, что и в этом случае не получается - попроси помощи. Это абсолютно нормально, когда у тебя что-то не получается. Главное не сдаваться, но не выгорать!

Есть и другие важные мысли, но пока этих достаточно для того, чтоб нам получилось выстроить грамотно работу. Начнём с проверки твоей вёрстки сайта, я буду закидывать моменты, которые буду подмечать, ты не стесняйся - задавай вопросы в комментариях. Постараюсь двигаться от простого к более сложному, но не обещаю) Если что-то непонятно из того, что я имею ввиду - уточняй. В общем, давай развиваться вместе)

P.s. очень рекомендую канал для обучения вёрстке "Фрилансер по жизни". Он после начала войны перешёл на украинский язык, но всё что он снимал до этого - более чем достаточно для того, чтобы обучиться крутой вёрстке сайтов)) Сам обучался помимо курсов по его видео. Важно правда, всё отрабатывать на практике
https://www.youtube.com/@FreelancerLifeStyle/playlists

**Comment by abakumovaa** [comment]
Илья, привет! Спасибо большое за такую обратную связь, очень приятно слышать такие слова! Тебя полностью поняла и услышала, буду работать над правками к проекту!
