### ISSUE TITLE
Ревью 02.12.24

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#11]
Думаю с этого момента закидывать всё в кучу, при необходимости выносить в отдельный ишью некоторые вопросы. Так будет удобнее)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/4aded39b-af1a-459f-acd9-8d8781eb1fe0)

![image](https://github.com/user-attachments/assets/3f14e477-8a86-46d2-8da7-ca9bb2976824)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/2188e705-cacc-4638-a2e7-90d2770b4257)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/d7807a00-c2a8-4d2a-9c5c-8181391ca101)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/c7aa6ef0-f5b3-4eae-97c3-c323ba7bda9f)

![image](https://github.com/user-attachments/assets/af597753-a115-46ad-be48-14f093611680)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/a21d78db-f84c-4e80-bc0e-5769fc24f121)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/15dea411-040e-436d-96eb-fe6fc4c46f35)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/54de05a6-3c6e-44eb-a6b3-10afe6af06a6)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/47b05113-9d5a-4ae5-b83a-bcf3e26d1cc4)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/f2e023e1-4648-4073-98c9-9e847a8abed2)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/dae18e34-62bd-456b-b33b-5dd092a17a59)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/fcb7dd85-b193-4a09-9ac5-ffcc536dcb8b)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/714e1005-7b0d-4ef5-8fc7-b932823d3022)

+ посмотри пожалуйста изображение, чела обрезало, как будто так не должно быть на мобилке

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/5187bdaf-3298-432f-ba8d-f1d500d59888)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/162d64af-d108-4d85-bf69-5e9ca067de50)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/ed0363ea-8c7a-4e9a-849e-34a29eb90d2c)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/7d64a869-f065-492a-acd3-fbea3881c327)

P.s. точнее, текст плохо читается, в таком случае либо подложку делают, либо изображение убирают, как на мекете

**Comment by Alexeenkov** [comment]
Смотрю, [ишью по оптимизации](https://github.com/abakumovaa/sos/issues/10) не выполнялось. Прошу выполнить, это критически важно, оптимизация изображений - это неотъемлемая часть работы фронтенд-разработчика, он всегда должен в работе думать об этом. Такие размеры изображений недопустимы

![image](https://github.com/user-attachments/assets/7ef17f2a-096c-4b60-b7f2-e108cb8497a0)

**Comment by Alexeenkov** [comment]
Сделай merge ветки "svg" в ветку "main". Перед слиянием сделай rebase ветки svg от ветки main. Если будут трудности - пиши, расскажу что да как

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/3943c740-858c-434c-b046-fb9cd09bb5a7)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/7f15454d-bdaa-4a17-85aa-5186a97a1461)

Пройдись по всем местам, где у тебя подключаются изображения, и проверь, как это реализовано. Здесь не нужен вообще тег picture, достаточно img. SVG поддерживается всем браузерами, можно смело использовать.

![image](https://github.com/user-attachments/assets/3ede0205-b0f4-47d0-a778-84d1f4dc8d8d)

**Comment by Alexeenkov** [comment]
Обсуждали составные (сложные) имена элементов, надо изменить, чтоб 1 слово было после двух подчеркиваний

![image](https://github.com/user-attachments/assets/99f9bbbc-f5f2-47d6-8f0f-1781969e8ead)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/d5489d7e-1f11-427e-a62b-71f802129ece)

Документация: https://developer.mozilla.org/ru/docs/Web/HTML/Element/label

**Comment by Alexeenkov** [comment]
Мелочь, но давай отступы поправим))
P.s. я скидываю скринами примеры одного какого-нибудь использования, но не забывай, что код дублируется в подобных элементах и надо править в нескольких местах. Во фреймворках эта проблема решается циклами и компонентным подходом к вёрстке.

![image](https://github.com/user-attachments/assets/ae1a483b-9ab3-4720-a08e-3a2a57b6fdb3)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/c39a64a2-6d03-4f9c-a04c-04a9bb715560)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/14b917d6-1904-4161-9af4-719173615671)

**Comment by Alexeenkov** [comment]
Пройдись ещё самостоятельно в конце, протестируй каждую секцию на всех разрешениях после внесения правок. Чтоб везде чётенько было, не терять время больше на эту задачу и переходить к следующей)

**Comment by Alexeenkov** [comment]
Перепиши пожалуйста на picture/source для всех разрешений (включая ретину) и форматов изображений логотипы

**Comment by abakumovaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74237440/391514964-c7aa6ef0-f5b3-4eae-97c3-c323ba7bda9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTI4OTgsIm5iZiI6MTczMzM1MjU5OCwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MTQ5NjQtYzdhYTZlZjAtZjViMy00ZWFlLTk3YzMtYzMyM2JhN2JkYTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZjAzNTg2M2Q3ZjFkNzQ0MTg2NTA1MDg4MWM4MWVlN2U5MTdlZGFjYTg3MzM2NjZkMGY3YjY1MmFmNzI1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.beyelrI9gs6lr73HmkaHJ9Jpi7S-ZPEjw7329KN4YVc)
> 
> ![image](https://private-user-images.githubusercontent.com/74237440/391517304-af597753-a115-46ad-be48-14f093611680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTI4OTgsIm5iZiI6MTczMzM1MjU5OCwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MTczMDQtYWY1OTc3NTMtYTExNS00NmFkLWJlNDgtMTRmMDkzNjExNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjhhOTg4NjNmNGRlODI5ZWI4Zjk4MjUzN2Q5N2RmMDBkY2MyM2UxMDk3MGYzYjlmZTBiMjc5ZjI5YTlmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1lERD4A-I5YUtPipcsjLuHPo5XAPSdjpq9G5o4uwmdU)

Не совсем поняла коммент, у меня вроде бы ничего не скачет и всё ок, все градиенты сделаны одинаково

**Comment by abakumovaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74237440/391520415-15dea411-040e-436d-96eb-fe6fc4c46f35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTI4OTgsIm5iZiI6MTczMzM1MjU5OCwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MjA0MTUtMTVkZWE0MTEtMDQwZS00MzZkLTk2ZWItZmU2ZmM0YzQ2ZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYTIyYTM4Njk1OTVmZjIwMzg5OGI1OTU4YjhhNmI0MmQwZjA0ZTkwZTAwMjI1NWZlY2E3MWVhYTIxNDQ4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DAShnTu53WBkS_rBmY5T4hG_K3Z3-4XQWiIqQFQBn9E)

Странно, у меня при таком же разрешении экрана всё ок...
![изображение](https://github.com/user-attachments/assets/cc5dc9af-612c-48db-a6a9-fa954f7ead4e)

**Comment by abakumovaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74237440/391520664-54de05a6-3c6e-44eb-a6b3-10afe6af06a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTI4OTgsIm5iZiI6MTczMzM1MjU5OCwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MjA2NjQtNTRkZTA1YTYtM2M2ZS00NGViLWE2YjMtMTBhZmU2YWYwNmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIyNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYmRhNWRmMTRmOTZlNTM1OTdlNWYzYjNlYWM5NmE0NGNiOTNiOWJkMDM0MzBlYTY3MWJhOTg5YWY3ODY0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IB4aQnK7S2F43qK-jiFim6tq-WmK0mtHM0y_lyCoD3Q)




> ![image](https://private-user-images.githubusercontent.com/74237440/391520664-54de05a6-3c6e-44eb-a6b3-10afe6af06a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTYyMTUsIm5iZiI6MTczMzM1NTkxNSwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MjA2NjQtNTRkZTA1YTYtM2M2ZS00NGViLWE2YjMtMTBhZmU2YWYwNmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIzNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZmRlZjg5Mzg3MWQ5NWM2MzgyZmRiY2FjODdmZDVkMjhmMTA0MmJlNGI2NmEyMDhjY2ZkNWQyZDE5MWI0MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OTulNzsSXiTlh4eu7sjBKfkj4AkX1XV32_oVV2TOAQ8)

И тут тоже, отображение отличается от твоего на скриншоте 
![изображение](https://github.com/user-attachments/assets/afb60ecf-a7c4-41be-828c-6701cb18ab2f)

**Comment by abakumovaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74237440/391512221-2188e705-cacc-4638-a2e7-90d2770b4257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTYyMTUsIm5iZiI6MTczMzM1NTkxNSwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MTIyMjEtMjE4OGU3MDUtY2FjYy00NjM4LWEyZTctOTBkMjc3MGI0MjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIzNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4M2RkYmE4ZWQxYzQ1NDg5NjRhMDMwMmNlMTBkODg5ZTJmZDVjMGQwNzE5YmFjY2JhNjVjM2ZmMWNlNDBkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bKfGqPVXdBuDleIUtRCrQAuyyCkFiuwk001r-dn4W5U)

Добавила плавность этому и всем интерактивным элементам

**Comment by abakumovaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74237440/391534359-ed0363ea-8c7a-4e9a-849e-34a29eb90d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTYyMTUsIm5iZiI6MTczMzM1NTkxNSwicGF0aCI6Ii83NDIzNzQ0MC8zOTE1MzQzNTktZWQwMzYzZWEtOGM3YS00ZTlhLTg0OWUtMzRhMjllYjkwZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIzNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYjJmNGY4NDdiOTQxOGQ1MTc3NDRhMmE5NWJmYTdhNDc1NmVkYTExNjBiY2ZjMTA3ZGUyYmRmOTE2MWRmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDxIZmflC7qLxMLTT4HNUKMBtixyeLq6X2pyvJXq7cc)

Изменила шрифт и толщину всем заголовкам и подзаголовкам при мобильном разрешении 326px
