### ISSUE TITLE
Вёрстка десктоп

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#2]
Здесь предлагаю вести беседу касаемо проблем, которые я найду на сайте по вёрстке на десктопе. Буду закидывать отдельными комментариями.

Upd: Пока что это всё, что я нашёл по десктопу при визуальном осмотре, в код не залезал и адаптив не смотрел (отдельные issues заведу). Предлагаю разобраться с этими вопросами не просто поверхностно - а прям изучить и разобраться на практике. Если чего-то не знаешь - гугли) Это важно научиться делать быстро и качественно. В первую очередь рекомендую знакомиться на MDN (как правило в первых ссылках вылезает), а потом уже из других источников. На ютубе можно посмотреть очень наглядно, много полезного материала - но дольше по времени. На стадии обучения не жалей время на это, важно сформировать в первую очередь мышление, а знания - дело наживное.

В понедельник продолжу проверку, надеюсь, у тебя будет время исправить данные комменты к тому времени)

**Comment by Alexeenkov** [comment]
Скинь пожалуйста макет сайта, по которому ты верстала) Мне крайне неудобно проверять, не зная, как оно должно быть

**Comment by Alexeenkov** [comment]
Кнопка на первом экране. Вёрстка должна быть надёжной и устойчива к переполнению контентом. Это касается почти любого блока. Как правило контент является динамичным - текст / изображения можно изменять, на разных языках может быть разная длина текста.
![image](https://github.com/user-attachments/assets/7dc31317-f53f-4105-9b1e-73d511e71a5b)

Чтобы такого не было, не надо ограничивать блоки по высоте - надо позволять им растягиваться. Также стоит добавить внутренние отступы для того, чтобы текст не прижимался к краям блока при переполнении.
![image](https://github.com/user-attachments/assets/f57f7697-6150-4377-8843-229e132d60e0)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/d1f85858-3154-4835-9602-3f504aaac77e)

**Comment by Alexeenkov** [comment]
![image](https://github.com/user-attachments/assets/8d776db4-4712-44da-a076-158c8e4aaf99)

![image](https://github.com/user-attachments/assets/886b2497-796f-44a3-bd84-9d2b7eb7ad00)

**Comment by Alexeenkov** [comment]
Не надо позволять логотипу расширяться больше определенных размеров, потому что он сломает вёрстку.
Плюс для ретина-дисплеев загружаются изображения в 2 или 3 раза больше, поэтому это важно.

![image](https://github.com/user-attachments/assets/ee398c6c-812e-440a-8a00-bf7c0cebcbc8)

![image](https://github.com/user-attachments/assets/778cd9ef-4980-4d68-b65f-d935fefb4f7f)

**Comment by Alexeenkov** [comment]
У многих кликабельных элементов часто добавляют внутренний отступ для того, чтобы клик срабатывал также на области вокруг элемента. Чтоб пользователя не заставлять целиться + на сенсорных экранах пальцем тяжело попадать.
Только учти, что внешний отступ надо будет уменьшить, чтоб как по макету было
Пройдись также по всем ссылкам и кнопкам на странице и поправь, где ещё подобные кейсы встречаются.

![image](https://github.com/user-attachments/assets/310307fd-06ca-45b0-9e34-794c1748dfe6)

**Comment by Alexeenkov** [comment]
Во 2-ом блоке при увеличении текста заголовка линия остаётся на том же месте. Она должна быть спозиционирована относительно родительского блока, для этого ему надо задать `position: relative`.

![image](https://github.com/user-attachments/assets/f09879a5-e3c1-4b8f-b4bc-fa193d1a2b56)

![image](https://github.com/user-attachments/assets/5e693dac-41c3-4f1d-8aad-03c4661b118f)

**Comment by Alexeenkov** [comment]
Как правило, у крайних элементов списка (кстати, тут должен быть список ul, а не на div в разметке) отступ не нужен, поэтому margin добавляется для всех элементов, кроме последнего

![image](https://github.com/user-attachments/assets/68938715-ea72-4632-bca4-733181c7d7b0)

![image](https://github.com/user-attachments/assets/f1ba7830-5490-4327-a01a-f7bbcd039380)

**Comment by Alexeenkov** [comment]
При переполнении контентом вёрстка ломается. Попробуй самостоятельно устранить проблему, если не получится, будем разбираться вместе (подсказка - надо поиграть с максимальной шириной и убрать центрирование)

![image](https://github.com/user-attachments/assets/764fe682-bd03-468c-86e5-da102d7253a9)

**Comment by Alexeenkov** [comment]
Здесь должен быть внешний отступ, а не внутренний (margin вместо padding).
Между блоками - внешний отступ, внутри конкретного блока - внутренний

![image](https://github.com/user-attachments/assets/45a2b092-74be-4893-b12e-4da883da900d)

**Comment by Alexeenkov** [comment]
По границам таблицы надо бы добавить внутренние отступы также справа и снизу, чтоб контент не прилипал

![image](https://github.com/user-attachments/assets/a5f75193-c1d6-4e9d-96c3-abc854fe0112)

**Comment by Alexeenkov** [comment]
Вероятно, в макете был пример не плейсхолдера, а уже введённого текста. Плейсхолдер не должен быть как основной текст, в данном случае прям плохо выглядит) Ему бы прозрачности накинуть или цвет побледнее..

![image](https://github.com/user-attachments/assets/d6b4a628-a20d-4f38-8d9e-0912f4d03d63)

**Comment by Alexeenkov** [comment]
Вижу, в подвале ты ограничила лого по высоте и ширине.. Но любое другое изображение уже не впишется адекватно

![image](https://github.com/user-attachments/assets/01c90339-6196-4ccb-acea-f72854329ba2)

Достаточно задать изображению пару свойств и уже будет вписываться любое изображение. Это важные свойства, если не знакома с ними - обязательно изучи

![image](https://github.com/user-attachments/assets/2cdb9f00-1866-4d72-95d5-a313d37387b7)

**Comment by Alexeenkov** [comment]
В этом блоке должны быть ссылки, между которыми разделяющая линия, не сплошным текстом

![image](https://github.com/user-attachments/assets/3f3e6bbc-1189-47e2-83b2-a73416eb647e)

**Comment by Alexeenkov** [comment]
Предложение по улучшению:
Хотелось бы при наведении на все интерактивные (кликабельные) элементы, с которыми пользователь может взаимодействовать, навесить какой-нибудь лёгкий hover-эффект. Он есть у тебя на кнопках, ссылках меню и т.д..
Но нет на ссылках в шапке например, или на стрелочках в слайдере

![image](https://github.com/user-attachments/assets/1a1fc068-7512-4848-beff-15c736db441c)

Исключением будет точно логотип, на него не нужен hover-эффект.
Также предлагаю накинуть везде где есть hover-эффект, лёгкую анимацию, а точнее плавность смены свойств.
Например: `transition: all 0.2s ease;`. Есили не знакома со свойством, обязательно изучи
https://www.youtube.com/watch?v=yZFg3cuq_LU

**Comment by Alexeenkov** [comment]
Все ссылки на внешние ресурсы должны иметь абсолютный путь и начинаться с `http` или `https`

![image](https://github.com/user-attachments/assets/ec01d51d-e95d-409f-906f-a5cf1e426f5e)

![image](https://github.com/user-attachments/assets/f288ef1f-4980-4902-ad1a-59a865023d37)

В данный момент ссылки не работают. Также на подобные ссылки обычно навешивается атрибут `target="_blank"`, чтоб пользователь не покидал сайт, а открывал новый в отдельной вкладке

**Comment by Alexeenkov** [comment]
Пока что это всё, что я нашёл по десктопу при визуальном осмотре, в код не залезал. Предлагаю разобраться с этими вопросами не просто поверхностно - а прям изучить и разобраться на практике. Если чего-то не знаешь - гугли) Это важно научиться делать быстро и качественно. В первую очередь рекомендую знакомиться на MDN (как правило в первых ссылках вылезает), а потом уже из других источников. На ютубе можно посмотреть очень наглядно, много полезного материала - но дольше по времени. На стадии обучения не жалей время на это, важно сформировать в первую очередь мышление, а знания - дело наживное.

В понедельник продолжу проверку, надеюсь, у тебя будет время исправить данные комменты к тому времени)

**Comment by abakumovaa** [comment]
> Скинь пожалуйста макет сайта, по которому ты верстала) Мне крайне неудобно проверять, не зная, как оно должно быть

Алексей, еще раз привет и еще раз спасибо за правки, всё максимально понятно и подробно расписано) Исправила все ошибки по твоим правкам, буду ждать обратную связь по коду и адаптиву!
Вот ссылка на макет - https://www.figma.com/design/ecQV1zkIU9eFaSIpDSEPi3/SOS?node-id=0-1&node-type=canvas&t=EquYLW6e1LBYuv3S-0

Если честно, мне не особо понравилось работать с данным макетом, тк. там не выстроены корректно отступы и размеры элементов, из-за чего я это всё подбирала на глаз) Обычно когда работала с макетами, использовала Pixel Perfect для подгона верстки под дизайн, но в этом проекте я этого не делала как раз из-за особенностей самого макета.

**Comment by Alexeenkov** [comment]
Привет! Это здорово, что всё понятно))

Понимаю, что макеты не всегда бывают точными и приходится определенные моменты реализовывать самостоятельно и высчитывать расстояния с трудом. Pixel Perfect я не требую, т.к. не считаю это грамотным подходом к работе и вообще ведению бизнеса) Но это лишь моё мнение. В коммерческой разработке часто (я бы даже сказал - постоянно) приходится сталкиваться с подобными проблемами - согласовывать с дизайнерами неточности, просить исправить, а если общаешься с ними не напрямую, а через менеджера, например - можешь догадаться, с какими трудностями приходится сталкиваться. Но это абсолютно нормально, в данном случае нам можно на свой взгляд решать какие-то проблемные вопросы (т.к. проект учебный), но это хорошая практика. Потому что часто приходится в реальной работе это делать - принимать решения по реализации самостоятельно. В данной работе здорово стремиться к лучшему результату - но не нужно быть перфекционистом. Иногда лучше чуть криво сделать, но чтоб всё работало и покрывало потребности бизнеса (а потом поправить), чем долго делать и не успеть с дедлайном. В этом я прям максимально уверен)

Я посмотрю твои правки и напишу новые комменты ниже по десктопу. Что-то ещё что найду интересное. Не только какие-то замечания, но и предложения. Ты можешь дискутировать, обсуждать, задавать вопросы - это всё поможет тебе быстрее прочувствовать всё как оно на самом деле происходит. Главное сформировать мышление - когда в следующий раз будешь реализовывать тот или иной компонент, вспоминай о нюансах, с которыми ты уже сталкивалась. Не забывай об опыте)

**Comment by Alexeenkov** [comment]
Тебе нужно вот этот элемент со стрелочкой зафиксировать относительно первой секции (главного экрана). Относительно окна браузера фиксировать неправильно, т.к. сама видишь - при разной высоте экрана пользователя стрелочка не учитывает другие элементы и наезжает поверх них

![image](https://github.com/user-attachments/assets/01791935-a4b6-4257-8329-2fafa26b9c89)

![image](https://github.com/user-attachments/assets/0a1925cb-2139-406d-9c34-68b4f000df3c)

P.s. задай родителю `position: relative;`

![image](https://github.com/user-attachments/assets/bf4330ce-c709-47fa-b3ee-71b6d60252d8)

**Comment by Alexeenkov** [comment]
При ширине экрана больше 1600px тень (градиент) теряется. Вроде как этой проблемы при прошлой проверке не было. После внесения правок, проводи пожалуйста регрессионное тестирование (всего сайта на всех разрешениях) для того, чтоб понимать, что всё остальное работает как прежде. Сейчас, пока опыта мало - рекомендую так делать. Это также поможет тебе смотреть на свою вёрстку по-новому, с разных сторон. Со временем (с опытом) ты будешь понимать при внесении правок - где ты могла что-то зацепить, и проверять только это. А пока рекомендую полностью проверять после большого количества правок)

![image](https://github.com/user-attachments/assets/0ef580a6-f32e-4688-8981-d19b2b7802c1)

**Comment by Alexeenkov** [comment]
В данном случае, из-за того, что ты добавила padding на некликабельный элемент, то мы не видим ожидаемого эффекта. Необходимо padding навесить на ссылку - тогда область вокруг ссылки будет кликабельна)

![image](https://github.com/user-attachments/assets/19d2321b-05be-4a9c-be8c-91014e65546b)

**Comment by Alexeenkov** [comment]
Понимаю, что есть макет и задача сделать как по макету, но в коммерческой разработке часто верстальщик может быть не согласен с дизайнером и согласовывает изменение макета по каким-либо причинам. Если договориться не получается - идёт к менеджеру или лиду и решает вопрос через него.

Здесь есть такой кейс - линия налезает на изображения. Ты реализовала правильно - по макету. Но на мой взгляд это выглядит отвратительно, поэтому предлагаю сделать так, чтоб линия не залезала на изображение ни при каких условиях))

![image](https://github.com/user-attachments/assets/60675433-2159-4241-b274-c396355493d5)

**Comment by Alexeenkov** [comment]
1) Линия залезла на кружочек, такого быть не должно

![image](https://github.com/user-attachments/assets/4f520034-325e-43c9-b57d-3cb88b0d8466)

2) Во втором пункте линия не доходит до кружочка - надо, чтоб она доходила ровно до следующего пункта, как это реализовано в первом.

![image](https://github.com/user-attachments/assets/60bfc86d-05ca-4165-ab8e-c6f7c599fda8)

3) Предлагаю также реализовать данный "аккордеон" таким образом, чтоб при загрузке страницы первый был сразу открыт (по умолчанию). Когда кликаешь на другие, открытый скрывается. Таким образом, всегда должен быть открыт только 1 пункт.

**Comment by Alexeenkov** [comment]
У данного сайта есть так называемая "Ширина контейнера". Это когда максимальная ширина контента фиксированная.

![image](https://github.com/user-attachments/assets/5a3c20e5-73c2-44b3-a364-cd44341eac1d)
![image](https://github.com/user-attachments/assets/bafd617b-d43d-4d58-a3ae-4629fa8fdd6a)

У тебя в данный момент ширина контента во всех секциях разная (видно по отступам до края окна браузера) - надо привести к виду, как на макете

**Comment by Alexeenkov** [comment]
1) Данная форма поплыла на изображение) Надо поправить

![image](https://github.com/user-attachments/assets/6ec214bb-6b15-4ce5-b707-68d9306556d1)

По макету (у тебя изначально более-менее было):

![image](https://github.com/user-attachments/assets/18db8110-4271-47d8-8a2d-ec5080416b45)

2) Прозрачность инпуту не нужна, прозрачность нужна была только для placeholder =)

3) Обрати внимание на отступы в инпуте и на макете - сильно разные и не на одном расстоянии тексты

4) Шрифты тоже разные (на всём сайте), на скринах выше видно. На цвет тоже обрати внимание

**Comment by Alexeenkov** [comment]
Почему приняла такое решение об отступах в таблице? Давай сделаем как по макету

![image](https://github.com/user-attachments/assets/c66653de-93d1-4b48-8d34-f36c568643d9)

**Comment by Alexeenkov** [comment]
1) Отступы должны быть одинаковые справа и слева

2) Текст апперкейсом написан должен быть

3) Нижний блок имеет справа другой отступ

![image](https://github.com/user-attachments/assets/c0ff697c-5c6a-4661-824e-70ffcd77aebb)

**Comment by Alexeenkov** [comment]
Здесь по макету имелось ввиду, что при наведении становится цвет соответствующий. Например, у ютуба красный, у фейсбука синий, а у твиттера голубой. У твича наверное фиолетовый)

На них тоже давай накинем transition, чтоб анимашка красивее была) И посмотри плз, где ты ещё упустила плавность (если мы решили сделать плавный эффект при наведении, то давай везде сделаем)

![image](https://github.com/user-attachments/assets/c4dfd4ee-796c-4ef4-a247-648c28c26b4d)

**Comment by abakumovaa** [comment]
Илья, привет! По этому issue сделала все правки в ветку main, можешь проверять.
По всем своим вопросам, которые писала тебе в телеге, тоже исправила:
- Добавила псевдо-тень в секцию home (в начало)
- Вроде как пофиксила проблему с аккордеоном и линией, перепривязав псевдоэлемент линию к контейнеру, а не заголовку и поигравшись немного с настройками высоты линии. 
- Исправила ошибку с отступами секций, выровняла всё
