### ISSUE TITLE
Предложение. Слайдер Swiper

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#3]
Давай пока скрипт, который делает пролистывание постранично, уберём вовсе. Здесь он не нужен - усложняет сайт, добавляет кучу багов, проблем с ним полно. Если есть желание научиться делать постраничную навигацию - лучше это научиться делать сразу на базе слайдера Swiper. Данная самописная реализация тебе ни к чему.

Но это уже следующий этап - это более сложно и пока предлагаю не реализовывать. Вернёмся, когда ты чуть больше освоишь вёрстку и изучишь JavaScript на базовом уровне. В пока пускай висит issue.

Начать можно с изучения слайдера Swiper (используется в большинстве коммерческих проектов, в том числе и у нас):
https://www.youtube.com/watch?v=ddbxsrGPRY0&list=PLM6XATa8CAG6IJvQBkrTTNZmpIcyS2Avk&index=23

Потренироваться как раз можно на этом слайдере (реализовать через свайпер)
![image](https://github.com/user-attachments/assets/1a15a4c5-b986-4367-8597-eb3cc06455c3)

Постраничная навигация сайта на базе этого слайдера - уже последний этап, но предлагаю к нему не переходить, т.к. это мало востребованный кейс. Сначала давай изучим базу.

Кстати, вот мой сайт, который я делал 3 года назад с постраничной навигацией на слайдере swiper. Это пример того, о чём я тебе говорю. Но мне кажется, что в твоём случае сайт не должен иметь постраничную навигацию.
https://alexeenkov.github.io/Agapov/

P.s. дизайн там ужасный, но я только учился и у меня не было опыта, поэтому делал по наитию)

**Comment by abakumovaa** [comment]
Постраничную навигацию убрала, как только сделаю реализацию слайдера через Swiper, добавлю тут коммент

**Comment by Alexeenkov** [comment]
Пока опустим момент с добавлением Swiper, при необходимости вернёмся к этому вопросу, на данный момент не стоит тратить время на это
