### ISSUE TITLE
Предложение. Работа с SVG

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#4]
Предлагаю чуть глубже окунуться в вопрос работы с SVG и разобраться, как можно с ними эффективно работать.
Ниже разбил изучение на шаги - переходи к следующему только когда отработала на практике предыдущий. Не нужно в теории всё просматривать и забивать голову кучей информации. Двигайся медленно, постепенно, всё отрабатывая собственноручно.
P.s. я накидал ссылок, рекомендую ознакомиться с ними и если вдруг не получается или что-то непонятно - обязательно гуглить и находить другую информацию, где объясняют другими словами. Только смотри на год создания статьи / видео. Чтоб не сильно древняя была инфа, раньше 2020 года статьи я уже не смотрю даже)

1) Вот коротенькое видео про знакомство с форматами изображений:
https://www.youtube.com/watch?v=YHV35GiXA-w

2) Оптимизировать SVG можно в данном сервисе (чтоб меньше кода было ненужного у SVG-иконки):
https://jakearchibald.github.io/svgomg/
Попробуй позакидывать SVG-иконки и посмотреть, как изменяется их код.

3) Вот тут ознакомься с тем, каким образом можно подключать SVG-иконку
https://webcademy.ru/blog/461/

4) Теперь стоит разобрать код SVG - что изменять, чтоб получить нужный результат
https://webcademy.ru/blog/499/

5) Реализуй на сайте hover-эффект для всех SVG-иконок, предварительно подключив их inline (прям в коде прописав).

6) Теперь займёмся немного оптимизацией. Объединим все svg-иконки в один файл, называемый svg-спрайт. И будем все иконки дёргать оттуда
https://siteok.org/blog/html/svg-sprajty/

**Comment by abakumovaa** [comment]
Всё сделала, запушила в ветку svg. Поначалу у меня была проблема с отображением иконок при использовании их через спрайт, я немного разобралась и у меня всё заработало, можешь проверять)

**Comment by Alexeenkov** [comment]
Кайф, прекрасная работа!
Давай только доведём до конца - сделаем через спрайты все изображения, за исключением логотипа

![image](https://github.com/user-attachments/assets/37e4940d-72bd-4dde-9589-489afecfeb92)

**Comment by Alexeenkov** [comment]
Эту стрелочку тоже надо красить при наведении в жёлтый, как и текст

![image](https://github.com/user-attachments/assets/46ef14c2-d8cf-4d30-878a-e095a3337296)

И эту тоже

![image](https://github.com/user-attachments/assets/6ffda2a8-b2c8-46d3-813e-f7d757f880d4)

Ну и эти тоже по-аналогии хотелось бы )

![image](https://github.com/user-attachments/assets/3eb20c6e-02ea-4850-9a02-c05d00a4b613)

**Comment by Alexeenkov** [comment]
Научились работать с SVG, с гитом тоже вроде нормалёк. Двигаемся дальше)
