### ISSUE TITLE
Переверстать блок с пунктами

### ISSUE THREAD

**Issue by Alexeenkov** [abakumovaa/sos#5]
Для каких-то небольших статических сайтов, где один раз сделал и ничего меняться не будет, такое решение вполне приемлемо. Но если я чуть увеличу или уменьшу длину текста или изменю шрифт - они ломаются (линии между пунктами имеют фиксированную высоту).

Задача со звёздочкой. Необходимо найти решение и сверстать таким образом, чтоб данная линия не зависела от высоты контента и всегда позиционировалась корректно (изменялась длина в зависимости от высоты блока). Это можно решить с помощью JS, но в идеале обойтись только вёрсткой и стилями)

Если не будет получаться, тогда предложу созвониться и попробовать найти решение в режиме реального времени совместно

![image](https://github.com/user-attachments/assets/369f6bfd-db8f-4b78-943e-66ca74b24de0)

**Comment by Alexeenkov** [comment]
По какой-то причине изображения не грузятся, но писал в телеге

**Comment by abakumovaa** [comment]
Забыла о том, что ты вынес данную ошибку в отдельный issue, поэтому продублирую своё сообщение на всякий случай сюда, из issue про верстку:
Вроде как пофиксила проблему с аккордеоном и линией, перепривязав псевдоэлемент линию к контейнеру, а не заголовку и поигравшись немного с настройками высоты линии.

**Comment by Alexeenkov** [comment]
Спасибо, уже выглядит лучше) Но проблема с переполнением контента не решена..

Происходят скачки при открытии/скрытии аккордеона

https://github.com/user-attachments/assets/62ca4e99-a4dd-46f7-bf38-95a54f66a860

Реализуй плз этот коммент, возможно пропустила) Это также поможет в решении проблемы со скачками (не полностью, но легче будет пофиксить)

![image](https://github.com/user-attachments/assets/f54e86b0-0267-49e1-8390-64d9dccd7eb7)

Ограничение блока по высоте и `overflow: hidden` - плохое решение

![image](https://github.com/user-attachments/assets/447aca11-912c-4168-8324-7fbc6644ba7a)

**Comment by Alexeenkov** [comment]
Решение обговорили, жду правки)

**Comment by Alexeenkov** [comment]
Во теперь красота, спасибо)
